# Use a imagem base do Python
FROM python:3.10-slim

# Instale as dependências
RUN pip install paho-mqtt

# Copie o código do cliente MQTT para o contêiner
COPY cliente.py /cliente.py

# Defina o diretório de trabalho
WORKDIR /app

# Execute o cliente MQTT
CMD ["python", "cliente.py"]
